name = "OOOpenSCADScriptMaker"
uuid = "8573d768-f811-4428-954c-7dd23508d2f2"
authors = ["josePereiro <jose.pereiro.personal@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
